name: Inputs Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the eniornment to deploy
        required: true
        default: dev
jobs:
  input:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Deploy the application to ${{inputs.environment}}"
    

    
  
