name: env
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  dev:
   env:
      APP_ENV: "test"
   runs-on: ubuntu-latest
   steps:
      - name: Use variables
        # Step level: Available only to this step
        env:
          APP_ENV: "uat"
        run: echo $APP_ENV


    
  
